### ISSUE TITLE
Difference between `obophenotype/human-disease-ontology` and `IGS/disease-ontology`?

### ISSUE THREAD

**Issue by dhimmel** [IGS/disease-ontology#1]
I am very excited to see that the Disease Ontology is moving to GitHub. I think this will really reduce the overhead for contributing.

I am confused about the difference between this [repository](https://github.com/IGS/disease-ontology) (`IGS/disease-ontology`) and the `obophenotype/human-disease-ontology` [repository](https://github.com/obophenotype/human-disease-ontology)?

Which one should we submit feature requests or corrections to? What is the difference between the two. Perhaps it would be worth clarifying in the README.

**Comment by elviram** [comment]
Hi Daniel,

the [repository](https://github.com/IGS/disease-ontology) (`IGS/disease-ontology`) was a quick reaction to sourceforge going down. The plan has always been to move to github and we will do so shortly. There will be an announcement and READMEs to explain it all.

Thank you for your interest in our work.

Best,
Elvira

**Comment by dhimmel** [comment]
And what is [`obophenotype/human-disease-ontology`](https://github.com/obophenotype/human-disease-ontology)? Until I saw this repo, I thought that was the official repo.

**Comment by elviram** [comment]
It is the repo for DO in OWL and additional files for that project. The original DO file is created in OBO and stored in sourceforge (https://sourceforge.net/projects/diseaseontology/).
We do look at tickets on both sites.

Best,
Elvira
