### ISSUE TITLE
Can we create a gitter.im room for DO?

### ISSUE THREAD

**Issue by seandavi** [IGS/disease-ontology#3]
https://gitter.im is a chat system (similar to Slack) that can be used for instantaneous communication.  Creating a "room" would allow folks to "chat" with each other in real time.  Integrations with github and other services.

**Comment by dhimmel** [comment]
@seandavi see https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/158. This repository "was a stop-gap measure when SVN went down for quite a few days" and should probably have its README updated. So in short, I think you're looking for [`DiseaseOntology/HumanDiseaseOntology`](https://github.com/DiseaseOntology/HumanDiseaseOntology).
